### ISSUE TITLE
Esri Raster Basemaps set for deprecation

### ISSUE THREAD

**Issue by karenmajewicz** [geobtaa/geoportal#420]
From Jim L.

Esri has deprecated a number of raster basemaps, including the one used by the geoportal.  See https://www.esri.com/arcgis-blog/products/arcgis-online/announcements/reminder-raster-basemaps-moved-to-mature-support/ and  https://github.com/BTAA-Geospatial-Data-Project/geoportal/blob/6fc6e408877ae902aa04d781a685da3752edc2bc/app/assets/javascripts/geoblacklight.js#L2

**Comment by karenmajewicz** [comment]
I think this is the tiled reference layer that replaces the one we were using: https://www.arcgis.com/home/item.html?id=30d6b8271e1849cd9c3042060001f425

**Comment by ewlarson** [comment]
Using OpenStreetMaps Standard by default.

On GeoDev:
https://geodev.btaa.org/

![Image](https://github.com/geobtaa/geoportal/assets/69827/6c8f4f59-a362-442e-bae3-dc924259f569)

**Comment by ewlarson** [comment]
Addressed in v5.6.0. Can this be closed now?
