### ISSUE TITLE
Safari browser blocking popups from map point icons on homepage

### ISSUE THREAD

**Issue by karenmajewicz** [geobtaa/geoportal#452]
### What happens:

1. Go to home page using Safari
2. Zoom into a point on the map
3. Click on the point
4. nothing happens

### What should happen:
1. Go to home page using Safari
2. Zoom into a point on the map
3. Click on the point
4. a little popup appears with the title of the associated resource and the ability to click on it and go to the item page

### More info

- Chrome and Firefox display these fine.
- Even with all privacy settings turned off, Safari does not show them
- No errors are reported in the Safari console

**Comment by mberkowski** [comment]
Additional: Amy confirms same behavior in Safari, noting that the cursor does turn to a crosshair but click does nothing, no console errors.

**Comment by ewlarson** [comment]
Apparently a Leaflet v1.7.1 bug: https://stackoverflow.com/a/65369228

Using a branch of GBL v4 with Leaflet v1.8.0 resolves the error. But Leaflet v1.8.0 breaks our homepage's Leaflet geosearch plugin: https://github.com/smeijer/leaflet-geosearch/issues/323

**Comment by ewlarson** [comment]
Newest release of leaflet-geosearch (v3.6.1) resolves the issue it had with Leaflet v1.8.0. Newest RC of GBL v4 includes Leaflet v1.8.0.

I'll upgrade us to GeoBlacklight v4.0.0-rc2 and that will close this issue.

**Comment by ewlarson** [comment]
Closing via [v4.6.0](https://github.com/geobtaa/geoportal/releases/tag/4.6.0)
