### ISSUE TITLE
Make the switch to Google Analytics 4

### ISSUE THREAD

**Issue by ewlarson** [geobtaa/geoportal#453]
See: https://support.google.com/analytics/answer/10759417

**Comment by karenmajewicz** [comment]
We are considering moving to a different analytics platform instead

**Comment by karenmajewicz** [comment]
Thanks for the info note - those limitations might not be a problem for us moving forward. We haven't had any non-UMN users actually use Google Analytics on their own and we may be reconsidering our need for Tableau. Our main Google Analytics usage has been that I (or Ryan) log into the platform and manually extract various statistics.

We are also considering other platforms beyond Matomo. (i.e., Fathom)

**Comment by ewlarson** [comment]
Need to add Matomo tracking snippet Michael sent me.

**Comment by karenmajewicz** [comment]
Added Matomo instead.

Will need to revisit to see if we need to retain Google Analytics in tandem going forward.

**Comment by karenmajewicz** [comment]
Check in about this in June. Matomo is working well and we should assess if we want to keep Google Analytics running in tandem.

**Comment by ewlarson** [comment]
Closing. Using Matomo only.
