### ISSUE TITLE
Web service full screen should be 100% height

### ISSUE THREAD

**Issue by karenmajewicz** [geobtaa/geoportal#457]
What should happen:

- user clicks full screen widget
- map takes up full screen

What is happening
- user clicks full screen widget
- map is same height, but full width (see image)

<img width="1512" alt="Screen Shot 2022-04-22 at 5 09 58 PM" src="https://user-images.githubusercontent.com/2367677/164802230-10915f6c-00f5-48f3-8ae7-aa700bff1b12.png">

**Comment by ewlarson** [comment]
Hmm... I'm not seeing this behavior myself. Do you have an example URL? Is this an issue in a particular browser?

**Comment by karenmajewicz** [comment]
Example: https://geo.btaa.org/catalog/7f48652a35424b97b2bc2542c4ef26ae_2

**Comment by karenmajewicz** [comment]
This seems to only happen in Safari
