### ISSUE TITLE
Put a "Recently Added" widget on homepage/search pages

### ISSUE THREAD

**Issue by karenmajewicz** [geobtaa/geoportal#458]
We would like to be able to highly recently added items somewhere. We could perhaps use the `date_created_dtsi` field?

**Comment by karenmajewicz** [comment]
Another idea is to add a Sort by "Date Added" to the sort options.

**Comment by ewlarson** [comment]
Sort option

![Image](https://user-images.githubusercontent.com/69827/202514372-77bb7449-4ef7-45e4-9738-47d6d76329ce.png)

Item show / Metadata 
![Image](https://user-images.githubusercontent.com/69827/202514396-4f3b9f34-4284-4a97-8b25-b027c0a91392.png)

**Comment by karenmajewicz** [comment]
This is useful and seems to be working correctly!

I don't love the inclusion of the ISO Time at the end of the value, but don't want to add another field just for display either.

**Comment by ewlarson** [comment]
Oh! We can format that date output however you want. Let me know what you prefer and I'll make it happen.

**Comment by karenmajewicz** [comment]
OK - I think `2022-09-26` would be a good value to display

**Comment by ewlarson** [comment]
Closing - Added sort option.
