### ISSUE TITLE
Selected item on index maps do not change color (Safari only)

### ISSUE THREAD

**Issue by karenmajewicz** [geobtaa/geoportal#459]
What should happen:
- go to a record with an OpenIndexMap
- select a polygon or point
- the selected item changes color

What happens in Safari:
- go to a record with an OpenIndexMap
- select a polygon or point
- there is no change to the color or highlighting for the selected item

**Comment by ewlarson** [comment]
Confirming this issue; it's actually GeoBlacklight/Safari bug. Will recreate issue upstream.

**Comment by ewlarson** [comment]
Upstream issue: https://github.com/geoblacklight/geoblacklight/issues/1223
