### ISSUE TITLE
Update multiple download links in Admin view

### ISSUE THREAD

**Issue by karenmajewicz** [geobtaa/geoportal#464]
With the new multiple download feature, the links displayed in the Geoportal admin view refer back to GEOMG.
![Screen Shot 2022-05-12 at 7 54 22 AM](https://user-images.githubusercontent.com/2367677/168079387-eb11f3af-0c8b-4bb8-949d-cc7b34daba27.png)

**Comment by ewlarson** [comment]
Hmm... Can you please add a link to a document where this error presents?
