### ISSUE TITLE
Increase the ImageMagick resource allocation

### ISSUE THREAD

**Issue by karenmajewicz** [geobtaa/geoportal#466]
@mberkowski  We have gotten numerous `cache resources exhausted` error messages after ingesting new items that have images. Perhaps we could try increasing the file sizes that ImageMagick can handle? 

Related issue #465 

Related info: https://stackoverflow.com/questions/68604202/imagemagick-cache-resource-exhausted

**Comment by mberkowski** [comment]
I do see a big memory spike this afternoon, the only such spike over 4 weeks of monitoring. The default limits we have in place are:

```
  <policy domain="resource" name="memory" value="256MiB"/>
  <policy domain="resource" name="map" value="512MiB"/>
  <policy domain="resource" name="width" value="16KP"/>
  <policy domain="resource" name="height" value="16KP"/>
  <!-- <policy domain="resource" name="list-length" value="128"/> -->
  <policy domain="resource" name="area" value="128MB"/>
  <policy domain="resource" name="disk" value="1GiB"/>
```

I think `16KP` means 16,000 pixels. Do you have images larger than that? I've seen images that big cause problems on IIIF things too.

**Comment by mberkowski** [comment]
I have bumped these to 20k pixels and 512MiB memory. No idea if hat will make a difference - if you can retry the ingest @karenmajewicz we can see what happens.

**Comment by karenmajewicz** [comment]
Thanks. I noticed this happening with this batch of images: https://geo.btaa.org/?f%5Bdct_isPartOf_sm%5D%5B%5D=d0177da4-b07c-4cee-ad3a-33279bf3473a&view=split, which I added in mid-May.

I don't think I have any extra large size images, but I am not sure as we are harvesting them from remote sources.

I will keep an eye on this and see if it makes a difference.

**Comment by mberkowski** [comment]
I've seen a couple more errors like this, and increased the policy limits again.

**Comment by ewlarson** [comment]
Seems fine now.
