### ISSUE TITLE
Is geoportal_uris.rake task still running monthly?

### ISSUE THREAD

**Issue by karenmajewicz** [geobtaa/geoportal#467]
I haven't received a broken link report since February.

**Comment by mberkowski** [comment]
I've been letting these jobs run again with more typical space in between to see if that changes the outcome. We'll know tomorrow.

**Comment by karenmajewicz** [comment]
July 2 job came through fine.

**Comment by karenmajewicz** [comment]
reopening: I haven't received these in my email since July- is the September one sitting on the server?

**Comment by mberkowski** [comment]
@ewlarson can you check that you have the latest geoportal-deploy which includes this commit? https://github.umn.edu/Libraries/geoportal-deploy/commit/6775dd5b197a559f215ac5e0a0a23032b0599b64

I see the last prod deploy was 7/15 but the uri jobs did not get set out of schedule.rb. A redeploy with up to date geoportal-deploy code should make this work again

**Comment by ewlarson** [comment]
Okok... I did not have that commit here locally. I've pulled the latest commits and will redeploy.

**Comment by mberkowski** [comment]
thanks and later I'll start running the job sequence manually to report out before Oct.

**Comment by ewlarson** [comment]
Deploy completed. Latest release is running on geoprod.
