### ISSUE TITLE
Newest items not fully indexed

### ISSUE THREAD

**Issue by karenmajewicz** [geobtaa/geoportal#468]
Noting a bit of odd behavior with latest ingest.  They don't appear to have fully indexed.

Example record: https://geo.btaa.org/catalog/8c7faafbee524234bed84d1591503077_0

- Clicking on the Provider value returns no results. (https://geo.btaa.org/?f%5Bschema_provider_s%5D%5B%5D=New+Jersey+Geographic+Information+Network+Open+Data+Portal)  It should show ~480 records

- Clicking on a value in the place name either returns no results or only items from other uploads (https://geo.btaa.org/?f%5Bdct_spatial_sm%5D%5B%5D=Union+Beach%2C+New+Jersey).

Maybe we need to reindex Solr? I am not sure of how to do that without messing up GEOMG...

**Comment by ewlarson** [comment]
@mberkowski / Could you please reindex GEOMG? There is a rake task: geomg:solr:reindex -- I'm pretty sure that's the name. 

Sorry I can't do it myself. I'm at a soccer tournament in Chicagoland. Give me a call if you have any questions. No laptop near me tho!

**Comment by mberkowski** [comment]
Already on it!

**Comment by mberkowski** [comment]
Reindexing is finished, but I do not see different results than initially reported.

**Comment by ewlarson** [comment]
Well that is mighty odd. Field facets for some records, but not some others.

To debug, I would be curious to see the value as indexed and the query Solr is seeing here.

**Comment by karenmajewicz** [comment]
Figured it out - it was a metadata thing - these records got marked as suppressed. I adjusted them and they are fine now.
