### ISSUE TITLE
This link: https://geo.btaa.org/catalog/ shows up in Google searches

### ISSUE THREAD

**Issue by karenmajewicz** [geobtaa/geoportal#470]
When doing a Google search for BTAA Geoportal, Google returns the homepage as the top result, and a page called "Explore maps and data" as the second, nested result. This second one links to https://geo.btaa.org/catalog/, which is not a correctly working page. It shows the page elements overlapping each other surrounded by white space.

Can we either fix that page or somehow change Google's results?

---------------------

## Google Search Results
![google](https://user-images.githubusercontent.com/2367677/176004270-b27fcabb-4103-4840-aa3c-bc6f7e28e4e3.png) 

## This page: https://geo.btaa.org/catalog/
![catalog](https://user-images.githubusercontent.com/2367677/176004258-0c24cbe6-9891-4ddf-bd28-4b804dd71454.png)

**Comment by ewlarson** [comment]
We'll redirect "/catalog" back to "/" going forward. Example:
https://geodev.btaa.org/catalog

**Comment by ewlarson** [comment]
This unfortunately breaks map-based search...

**Comment by ewlarson** [comment]
Fixed by updating our maps baseUrl to root.
