### ISSUE TITLE
Export function for OGC web services not working

### ISSUE THREAD

**Issue by karenmajewicz** [geobtaa/geoportal#473]
**What happens:**
1. Go to a record with an OGC web service
2. Click the Download button
3. The options:
     - "Original {format}" - works as expected
     - one or more **"Export" - this does not list the export format but displays as a link that does not go anywhere**

Example record: https://geo.btaa.org/catalog/harvard-g6800-1903-p4, https://geo.btaa.org/catalog/stanford-pp624tm0074

**Comment by ewlarson** [comment]
Looks like a couple things happening here.

1. A B1G Geoportal export labeling bug
2. Bad JSON metadata?

Here's what happens in the Geoportal:
![Image](https://user-images.githubusercontent.com/69827/178282768-8d9f45f8-ecfa-40a2-b0eb-83e3fc2f729f.png)

Here's what vanilla GBL v4 looks like:
![Image](https://user-images.githubusercontent.com/69827/178282939-b10b5e00-11fd-484a-9b81-498d1f510e92.png)

The "download" call appears to time out:

```
Started GET "/download/harvard-g6800-1903-p4?type=geotiff" for ::1 at 2022-07-11 09:02:42 -0500
Processing by DownloadController#show as JSON
  Parameters: {"type"=>"geotiff", "id"=>"harvard-g6800-1903-p4"}
Unpermitted parameters: :type, :id
DEPRECATION WARNING: Blacklight 8 will filter out non-search parameter, including: id and type. (called from permit_search_params at /Users/ewlarson/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/blacklight-7.27.1/lib/blacklight/parameters.rb:77)
Solr query: get get {:qt=>nil, :ids=>"harvard-g6800-1903-p4"}
Solr fetch (14.5ms)
Download timed out https://geodata-proxy.lib.harvard.edu/geoserver/proxy/requestfile/wms/reflect
Completed 200 OK in 16367ms (Views: 1.5ms | ActiveRecord: 0.0ms | Allocations: 31575)
```

Clicking on the URL returned in the alert bar returns this:
![Image](https://user-images.githubusercontent.com/69827/178284158-61933206-be11-4d95-a34a-399b475ae1c6.png)

Is it possible the dct_references value here is inaccurate?
```json
  "dct_references_s": "{\"http://www.opengis.net/cat/csw/csdgm\":\"https://raw.githubusercontent.com/harvard-library/harvard-geodata/main/fgdc/G6800_1903_P4.xml\",\"http://schema.org/DownloadAction\":\"https://geodata-proxy.lib.harvard.edu/geoserver/proxy/downloadfile\",\"http://www.opengis.net/def/serviceType/ogc/wfs\":\"https://geodata-proxy.lib.harvard.edu/geoserver/proxy/requestfile/wfs\",\"http://www.opengis.net/def/serviceType/ogc/wms\":\"https://geodata-proxy.lib.harvard.edu/geoserver/proxy/requestfile/wms\"}",
```

**Comment by ewlarson** [comment]
Upstream related issue: https://github.com/geoblacklight/geoblacklight/pull/1236

**Comment by ewlarson** [comment]
Closing issue with GBL v4rc3 release.
