### ISSUE TITLE
Map clusters do not display the expected number of results.

### ISSUE THREAD

**Issue by karenmajewicz** [geobtaa/geoportal#475]
User feedback:

> Description: The clustering on your results page is only showing a maximum of 100 records. Additionally, when selecting facets for filtering, it does not always result in the cluster number being equal to or smaller than the number of records that resulted from the filtering.

**Comment by ewlarson** [comment]
Closing via https://github.com/geobtaa/geoportal/commit/ed84a5be149daf121d09c0939a2c0510ab4d02ce
