### ISSUE TITLE
Popup tools blocked when item is Suppressed

### ISSUE THREAD

**Issue by karenmajewicz** [geobtaa/geoportal#476]
When an item is Unpublished, pop-up boxes do not work: Metadata, Web Services address, and Cite. This is not really a problem.

However, this also occurs when items are marked "Suppressed". That field is intended for items that are Published, but not searchable. These items should be able to display popups.

**Comment by karenmajewicz** [comment]
Example: https://geo.btaa.org/catalog/4d045025-4160-49c3-a366-0e4d5141a742

**Comment by ewlarson** [comment]
Hmmm... the example above appears to now be published. Do you have another example at hand?

**Comment by karenmajewicz** [comment]
Here is an example: https://geo.btaa.org/catalog/t027r22w4fc01  This item is suppressed=true.  The metadata link doesn't display.

**Comment by ewlarson** [comment]
The basic issue here is that we're querying for the `/citation` or `/web_services` pages passing along our default Solr params, which include: `'fq' => ["#{Settings.FIELDS.B1G_PUBLICATION_STATE}:published"]`

That filter is important to prevent unpublished items from appearing in search results, but we need to override it when viewing these item "attribute" views.

**Comment by ewlarson** [comment]
Ahhh... okok. That attribute works essentially the same way, filtering on it is baked into our search_builder.

**Comment by ewlarson** [comment]
Fixed this one on https://geodev.btaa.org/catalog/t027r22w4fc01
![suppressed](https://user-images.githubusercontent.com/69827/201787985-44a0840c-c483-46d5-af6c-e2b3cb66e917.gif)
