### ISSUE TITLE
Feedback spam has been increasing

### ISSUE THREAD

**Issue by karenmajewicz** [geobtaa/geoportal#478]
We used to receive spam very infrequently. In the past week, we are starting to get about one per day.  What strategies can we put in place to prevent this from getting out of control?

**Comment by mberkowski** [comment]
@karenmajewicz I assume you are referring to spam via https://geo.btaa.org/feedback?

**Comment by karenmajewicz** [comment]
Yes - https://geo.btaa.org/feedback - the messages get forwarded to a few inboxes. It's not a ton of spam, but it does appear to be slowly growing. Perhaps a more complex captcha would help?

**Comment by karenmajewicz** [comment]
Feedback spam has become fairly rare. Closing this unless it becomes an annoying issue again.
