### ISSUE TITLE
Raise the factored weight for the title field for text search algorithms 

### ISSUE THREAD

**Issue by karenmajewicz** [geobtaa/geoportal#479]
When performing text searches for items, the title field should be the most prominent factor affecting the relevancy.

Currently, we are seeing odd results for certain searches. For example searching for "minneapolis parks" brings up many results, but the record titled "Parks [Minneapolis, Minnesota] {2015}" is far below many maps that only have the word park in the keywords.

**Comment by karenmajewicz** [comment]
### First page of search resluts for "Minneapolis parks"
<img width="1050" alt="Screen Shot 2022-09-21 at 4 13 48 PM" src="https://user-images.githubusercontent.com/2367677/191611877-faf7745a-b442-4a8b-960e-b958527f8fe3.png">


### Third page of search resluts for "Minneapolis parks"
<img width="405" alt="Screen Shot 2022-09-21 at 4 14 56 PM" src="https://user-images.githubusercontent.com/2367677/191611913-5d058e97-d13a-4882-8bcf-231ce8a38f89.png">


### Sixth page of search resluts for "Minneapolis parks"
<img width="408" alt="Screen Shot 2022-09-21 at 4 14 17 PM" src="https://user-images.githubusercontent.com/2367677/191611806-65921653-747b-4696-bc99-c220f6333da1.png">

**Comment by karenmajewicz** [comment]
Related: How are results ordered when the algorithm is equal?  For example, searching for "parks" brings up a ton of records. Most at the top are ones with lower quality titles. Does a shorter title come up as more relevant?

<img width="1053" alt="Screen Shot 2022-09-21 at 4 19 02 PM" src="https://user-images.githubusercontent.com/2367677/191612635-25ec6de6-4317-4cf5-b446-0c90b4c81d1e.png">

**Comment by karenmajewicz** [comment]
Another experiment. I edited the record for "Parks [Minneapolis, Minnesota] {2015}" and now a search for "Minneapolis parks" is a little different. However, the results are still odd. 

<img width="622" alt="Screen Shot 2022-09-21 at 4 25 06 PM" src="https://user-images.githubusercontent.com/2367677/191613882-e4b9ba5c-7f13-4b27-a35f-1960479087fe.png">


Result #4 has the word "Park" only in the title

Result #5 has this:

Title: `Parks` [Minneapolis, Minnesota] {2015}
Alternative Title: `Parks`
Description: This dataset displays city `parks` in Minneapolis.
Subject : `Parks`
Keyword: `Parks`, `Park`

`
Note - this is still the same whether or not there are brackets surrounding the word Minneapolis in the title

**Comment by karenmajewicz** [comment]
Here is what happens when searching "Parks Minneapolis"

<img width="634" alt="Screen Shot 2022-09-21 at 4 31 22 PM" src="https://user-images.githubusercontent.com/2367677/191614245-29094c88-c5d6-4b66-aa10-33f4dd56b9a4.png">


This is a better result. However, the record called "Parks: Hennepin County, Minnesota" shows up as #70. This record has `Minneapolis` in the spatial coverage field. This result shows up below many records that do not even have the word `Park` or `Minneapolis` in the title.

**Comment by ewlarson** [comment]
Okay, there are a lot of examples and questions here. Going through them in order...

- - - -

For the first example, minneapolis parks, we can update the title boost to drive the best results up to the top of the list. If we update our `solrconfig.xml` file to heavily boost the title field, we can get "Parks [Minneapolis, Minnesota] {2015}" to the top result.

solrconfig.xml
```diff
- dct_title_ti^9
+ dct_title_ti^70
```

70 is the minimum boost to make "Parks [Minneapolis, Minnesota] {2015}" the top result.

After that change the result list would be:

1. [Parks [Minneapolis, Minnesota] {2015}](http://localhost:3001/catalog/a1847c4cc69940f99b46b16e2b4fe7e3_0)
2. [Plat of Minneapolis and St. Louis Park](http://localhost:3001/catalog/p16022coll245:916)
3. [Park Commissioner Districts: Minneapolis, Minnesota](http://localhost:3001/catalog/f146a8db343044a68dc1dfbff06f5605_0)
4. [Downtown Parking: City of Minneapolis, Minnesota](http://localhost:3001/catalog/a65e42e4320a44ccb27bf496793b6537_5)
5. [Transitional Parking: City of Minneapolis, Minnesota](http://localhost:3001/catalog/a65e42e4320a44ccb27bf496793b6537_1)
6. [Park Commissioner Districts [Minneapolis, Minnesota] {2022}](http://localhost:3001/catalog/cityoflakes::minneapolis-park-commissioner-districts-2022)
7. [SBSP NiceRide Parking System [Minneapolis, Minnesota] {2022}](http://localhost:3001/catalog/cityoflakes::sbsp-2022-niceride-parking-system)
8. [1917 general plan Minneapolis, Minnesota : showing complete street and park system](http://localhost:3001/catalog/p16022coll245:973)
9. [Washburn Park, 1886 : comprising parts of S.15-T28N-R24W, Minneapolis, Minnesota](http://localhost:3001/catalog/p16022coll245:982)
10. [City of Minneapolis](http://localhost:3001/catalog/p16022coll245:908)

----

How does Solr sort results with the same score? That's determined by our default sort settings:

solrconfig.xml
```xml
<str name="sort">score desc, dct_title_sort asc</str>
```

We can change this default sort anyway we want. We could add fields like `gbl_indexYear_im` if we want.

----

Editing the record to try and boost/change results...

You definitely could try to boost a record by editing the metadata, but I think a lot of our boosts are quite low. We might need heavier boosts to make it easier to differentiate records.

----

For, parks minneapolis, with my heavy title boost, we'd have these results:

1. [Parks [Minneapolis, Minnesota] {2015}](http://localhost:3001/catalog/a1847c4cc69940f99b46b16e2b4fe7e3_0)
2. [Plat of Minneapolis and St. Louis Park](http://localhost:3001/catalog/p16022coll245:916)
3. [Downtown Parking: City of Minneapolis, Minnesota](http://localhost:3001/catalog/a65e42e4320a44ccb27bf496793b6537_5)
4. [Park Commissioner Districts: Minneapolis, Minnesota](http://localhost:3001/catalog/f146a8db343044a68dc1dfbff06f5605_0)
5. [Transitional Parking: City of Minneapolis, Minnesota](http://localhost:3001/catalog/a65e42e4320a44ccb27bf496793b6537_1)
6. [Park Commissioner Districts [Minneapolis, Minnesota] {2022}](http://localhost:3001/catalog/cityoflakes::minneapolis-park-commissioner-districts-2022)
7. [SBSP NiceRide Parking System [Minneapolis, Minnesota] {2022}](http://localhost:3001/catalog/cityoflakes::sbsp-2022-niceride-parking-system)
8. [1917 general plan Minneapolis, Minnesota : showing complete street and park system](http://localhost:3001/catalog/p16022coll245:973)
9. [Washburn Park, 1886 : comprising parts of S.15-T28N-R24W, Minneapolis, Minnesota](http://localhost:3001/catalog/p16022coll245:982)
10. [City of Minneapolis](http://localhost:3001/catalog/p16022coll245:908)

**Comment by ewlarson** [comment]
Closing via https://github.com/geobtaa/geoportal-solr-config/pull/10
