### ISSUE TITLE
Create a public interface view showing Solr scoring

### ISSUE THREAD

**Issue by karenmajewicz** [geobtaa/geoportal#480]
This idea is to create a debug view that Team Members can use to understand the relevancy scoring in Solr.  Users could investigate and see things like why some items float to the top of a search results list or are not showing up on the first page of results.

This will help us to tweak the algorithm or fix metadata issues. It will also help troubleshoot the mysterious scoring for the spatial search algorithms.

**Comment by ewlarson** [comment]
Closing via https://github.com/geobtaa/geoportal/commit/beb5d9054bf6f601474b40696d66ed6cc6009573

Add `&score=true` and/or `&explain=true` to the search result URL see Solr's explain output for each search result. Example:
https://geodev.btaa.org/?search_field=all_fields&q=iowa+farms&explain=true
