### ISSUE TITLE
Disable scrolling zoom on preview pane until user clicks on it.

### ISSUE THREAD

**Issue by karenmajewicz** [geobtaa/geoportal#483]
The layout of the search results and item page means that when a user selects an item from the search results page, their cursor will be over the IIIF/web service preview.  If the user begins to scroll down to see the metadata, the item in the preview will start to zoom.

One way to get around this is to adjust the Leaflet settings so that the zoom only occurs when a user has clicked on the preview pane. Here is a discussion about that: https://gis.stackexchange.com/questions/111887/leaflet-mouse-wheel-zoom-only-after-click-on-map/111888

**Comment by ewlarson** [comment]
I think for the item page, we should keep that as fixed-width for now. That page will need a little more polish to look/work well with a fluid layout.

**Comment by ewlarson** [comment]
Test driving Leaflet.Sleep -- seems to be the most popular choice (used at Harvard and Cornell).

Enabled:
https://geodev.btaa.org/catalog/a5e99776bbab494da81deb9c79bab31d_0

<img width="1728" alt="Screen Shot 2022-11-17 at 2 48 38 PM" src="https://user-images.githubusercontent.com/69827/202556771-9b68149c-9f0a-474d-9be0-bf83e8f70c6c.png">
<img width="1728" alt="Screen Shot 2022-11-17 at 2 48 57 PM" src="https://user-images.githubusercontent.com/69827/202556777-062fea7f-ca8b-473a-8afd-649b338f919c.png">
<img width="1728" alt="Screen Shot 2022-11-17 at 2 49 04 PM" src="https://user-images.githubusercontent.com/69827/202556789-014f6628-2a2a-4a51-ae1e-128d0ce07832.png">

**Comment by karenmajewicz** [comment]
I think this is pretty nice. The "Hover" aspect is a little confusing. Is there a length of time specified for that? Like if you just scroll over it, the map doesn't wake. But, if your scroll ends while the cursor is over the map, it does wake. Slightly unexpected.

**Comment by ewlarson** [comment]
The default config options are here:
https://github.com/CliffCloud/Leaflet.Sleep#config

So, we'd be able to tweak anything here. We can turn hover off if you like?

**Comment by karenmajewicz** [comment]
Maybe we should turn off the hover option for now. That is what Harvard & Cornell are doing.

**Comment by ewlarson** [comment]
Turned off hover. Closing this one. Reopen if you need anything else adjusted.
