### ISSUE TITLE
Review mobile usability issues

### ISSUE THREAD

**Issue by karenmajewicz** [geobtaa/geoportal#489]
Here's an autogenerated message from Google Search Console that came in this week:

> Search Console has identified that your site is affected by 3 Mobile Usability issue(s). The following issues were found on your site.
> 
> Top Issues
> 
> Content wider than screen
> Clickable elements too close together
> Text too small to read

**Comment by ewlarson** [comment]
I don't think I have access to GSC for the Geoportal. Can you add me (ewlarson@gmail.com) as a User?

**Comment by karenmajewicz** [comment]
OK, added.

**Comment by karenmajewicz** [comment]
This was just for a few records. Closing.
