### ISSUE TITLE
"Browse all..." link under related records widget broken

### ISSUE THREAD

**Issue by karenmajewicz** [geobtaa/geoportal#493]
The relation widgets have a link that takes the user to a "Browse all..." list of records. This link is not working - it simply takes the user back to the homepage.

Examples:

https://geo.btaa.org/catalog?f%5Bdct_isPartOf_sm%5D%5B%5D=05d-01

https://geo.btaa.org/catalog?f%5Bdct_source_sm%5D%5B%5D=08a-01

https://geo.btaa.org/catalog?f%5Bpcdm_memberOf_sm%5D%5B%5D=2787a9e8-0bef-452e-9e5f-e83042c193b4

**Comment by karenmajewicz** [comment]
Could this commit have affected that? https://github.com/geobtaa/geoportal/commit/a2c413e6f04fb793ffd3dec5da3c8fe1a33d813d

**Comment by ewlarson** [comment]
Yes, gotta be fallout from that redirect commit. 🤦

**Comment by karenmajewicz** [comment]
Other clickable facetted searches don't include the catalog part of the URL. Could this be removed from the GeoBlacklight behavior? This links works:
https://geo.btaa.org/?f%5Bdct_isPartOf_sm%5D%5B%5D=05d-01

**Comment by ewlarson** [comment]
The whole /catalog URL path comes upstream from Blacklight. We'll have to look at how those relation browse links are generated, but it would be nice to 86 /catalog wherever we can.

**Comment by ewlarson** [comment]
`blacklight_path` would do what we want instead of `search_catalog_path`
https://github.com/geoblacklight/geoblacklight/blob/53f41997ad16465dca559bbd36ca87b394b9f744/app/views/relation/_relations.html.erb#L11

We/GBL don't seem to standardize the use of these paths anywhere, so some schools probably prefer /catalog paths, whereas I'd rather not have /catalog in our links.

**Comment by ewlarson** [comment]
Fixed our naive relationship browse test. Swapped search_catalog_path for blacklight_path. Fix is up on geodev for review:
https://geodev.btaa.org/catalog/88cc9b19-3294-4da9-9edd-775c81fb1c59

Also swapping all other search_catalog_path uses to blacklight_path.

I'll cut a release and push this to prod this afternoon.
