### ISSUE TITLE
Troubleshoot IIIF zoom levels for Nebraksa maps

### ISSUE THREAD

**Issue by karenmajewicz** [geobtaa/geoportal#494]
The latest batch of maps from Nebraska exhibit odd behavior in our IIIF viewer. The page loads as normal, but then the image zooms in to the top corner at maximum zoom. Is this just a setting on Nebraska's server? Does it have anything to do with our expanded viewer size?

Example: https://geo.btaa.org/catalog/RUMSEY_8_1_33780_1171496

**Comment by ewlarson** [comment]
Here's the IIIF Manifest for that item:
https://mediacommons.unl.edu/luna/servlet/iiif/m/RUMSEY~8~1~317904~90086911/manifest

If you view it in the [online Mirador demo](https://mirador-dev.netlify.app/__tests__/integration/mirador/) or the [Universal Viewer demo](https://uv-v4.netlify.app/#?manifest=https://mediacommons.unl.edu/luna/servlet/iiif/m/RUMSEY~8~1~317904~90086911/manifest&c=&m=&cv=&xywh=64%2C511%2C2536%2C1401), the same behavior occurs.

Must be something about their stuff causing this behavior.

**Comment by karenmajewicz** [comment]
Thanks - I will notify our Nebraska contacts to let them know what we are seeing.
