### ISSUE TITLE
Add Rutgers to Licensed Resource access keys

### ISSUE THREAD

**Issue by karenmajewicz** [geobtaa/geoportal#500]
We need to add Rutgers to our list of Licensed Resources 

For this file: https://github.com/geobtaa/geoportal/blob/4057654be6336c3b1b2475b881fc9a7226a8aef0/app/helpers/application_helper.rb#L57

Can we add this line: '14'=> 'Rutgers University-New Brunswick'

Is there anything else that would need to be done? (We are still waiting on an SVG icon from Rutgers)

**Comment by ewlarson** [comment]
Was able to make a grayscale icon of Rutger's shield logo.

![Image](https://user-images.githubusercontent.com/69827/224844513-3f413888-c296-43e6-ab61-1a2ea45f42e0.png)

**Comment by karenmajewicz** [comment]
I just realized we need to add this to GEOMG as well - the current dropdown list for this field only includes the first 13 institutions.

![Image](https://user-images.githubusercontent.com/2367677/225049005-d2b175d9-975d-4eb7-be03-6fc3f99318d9.png)
