### ISSUE TITLE
Consider how to display complex geometry in map inset

### ISSUE THREAD

**Issue by karenmajewicz** [geobtaa/geoportal#505]
Related to #477

The map inset will show both the geometry and the bounding box. If they represent different shapes, they appear on top of each other. Example: https://geodev.btaa.org/catalog/camel-1006400

Would it be possible to use a different color for the geometry overlay?  With some explanatory text?  Just brainstorming here on making this more intuitive....

**Comment by karenmajewicz** [comment]
Circling back to this - for an upcoming article, I am planning to document some examples on how the complex geometry is useful. The case might be stronger if the bbox looks different from the geometry polygons. A few candidates I might use:

U.S. Air Force. (2016). Aeronautical Planning Charts: Iran AP-12. U.S. Air Force. Available from: https://geo.btaa.org/catalog/camel-1015121- shows how a map warps over a large area


Hondius, Hendrik, 1597-1651. Appendix Atlas of the British Isles and Northern Europe, Jansson, Jan, 1588-1664. Appendix Atlas of the British Isles and Northern Europe, Mercator, Gerhard, 1512-1594, Vignaud, Henry, 1830-1922, former owner.. (n.d.). Anglesey; Garnesay; Wight olim vectis; Iarsay; Per Gerardum Mercatorem.; Title on verso: Isles d'Anglesey Wight Jarsay et Garnesay. Available from: https://geo.btaa.org/catalog/c8b46b52-0846-4abb-ba56-b484064f84ac - This pages has 4 inset maps on one page

**Comment by ewlarson** [comment]
For complex geoms, we could style the bbox like so:

![Screenshot 2024-02-29 at 11 59 57 AM](https://github.com/geobtaa/geoportal/assets/69827/7de68e37-eb81-4279-84d4-dfce71dc889c)

We have a lot of control here: color of the line, solid vs. dashed, etc. In the screenshot above, I've made it a dashed line with the same color as the geojson polygon.

**Comment by ewlarson** [comment]
The second example.
![Screenshot 2024-02-29 at 12 07 19 PM](https://github.com/geobtaa/geoportal/assets/69827/c24952d0-0fad-4161-8c82-e613c53ff5c1)

**Comment by karenmajewicz** [comment]
Looks good.
