### ISSUE TITLE
Add clickable hyperlink functionality to Display Note

### ISSUE THREAD

**Issue by karenmajewicz** [geobtaa/geoportal#529]
We often add links in the Display Note field that users should be able to click on.  

Maybe this should be in default GeoBlacklight?

**Comment by ewlarson** [comment]
We can implement this locally, and open a PR for the feature in GBL for the Winter Code Sprint.

**Comment by ewlarson** [comment]
Do you have an example doc for this displayNote link feature?

**Comment by karenmajewicz** [comment]
https://geodev.btaa.org/catalog/test
