### ISSUE TITLE
Deprecate URI Analysis Jobs

### ISSUE THREAD

**Issue by karenmajewicz** [geobtaa/geoportal#538]
The last URI Analysis report (Oct 2023) resulted in an empty file. I think it is time to disable this rake task and replace it with a different workflow.

Reasons for deprecating this job:

- [ ] Instead of a timed monthly process, this should be a task that can be triggered manually ([#43 ](https://github.com/geobtaa/geomg/issues/43))
- [ ] The task returns too many false positives for links that actually do work. We end up with thousands of items to check and it is not realistic to sort through the list and fix everything ([#428](https://github.com/geobtaa/geoportal/issues/428))
- [ ] We should remove a check on the base URLs for GeoServers as these always return as broken (ex https://geowebservices.stanford.edu/geoserver/wms)
- [ ] We now reharvest from ArcGIS Hubs every week (~11,000 items) and don't need to check them anymore.
- [ ] Checking every single record seems to be a heavy load on the server, and we don't always need to do that. It would be easier to manage if we checked designated subsets at one time, like just one Provider or Resource Class.

----------

I would be up for replacing this task with something in GEOMG or with an external process that I run on exported records. At any rate, we should disable it for now while working on identifying broken links another way.

**Comment by ewlarson** [comment]
URI Analysis is no longer in the production schedule.rb file.
