### ISSUE TITLE
Ruby - Upgrade to latest v3.3.0

### ISSUE THREAD

**Issue by ewlarson** [geobtaa/geoportal#566]
We're running Ruby v3.0.3, which has an EOL of 4/1/2024. We should upgrade Ruby to the latest release v3.3.0.

I ran our Rails 7.0 branch CI test suite over Rubies 3.1, 3.2, and 3.3 and they all pass.

**Comment by mberkowski** [comment]
3.3.0 is now default on dev, pending evaluation

**Comment by mberkowski** [comment]
For future: Changing a version like this also requires changing it in capistrano deploy.rb and making sure the puma deployed by ansible uses the right one since it's possible for multiple rails apps to use different ones.

**Comment by ewlarson** [comment]
Running Rails 7 and Ruby 3.3 on production now.
