### ISSUE TITLE
Add attribution and rights for basemaps.

### ISSUE THREAD

**Issue by karenmajewicz** [geobtaa/geoportal#571]
From a feedback message:

> I'm not sure if the embeded maps are compliant with the OpenStreetMap attribution requirements. By my reading of https://osmfoundation.org/wiki/Licence/Attribution_Guidelines#Interactive_maps there should be some attribution for the map source. Could you check on this? ...  I think both the default (Esri) and OpenStreetMap selected layers should include attribution to OSM since both are pulling OSM data (street edits on OSM I made are showing on both styles). I'm not seeing attribution, if I'm missing it could you direct me to where it is included?

I don't see any attribution on our basemaps. Other GeoBlacklight instances do have them.

**Comment by ewlarson** [comment]
Use an (i) feature to popup the attribution.
