### ISSUE TITLE
Upgrade to GeoBlacklight version 4.4

### ISSUE THREAD

**Issue by karenmajewicz** [geobtaa/geoportal#574]

**Comment by karenmajewicz** [comment]
I am anticipating a problem with Clover regarding the lack of generated download button.  For individual items, I can add a direct download.  However, for an atlas, I wouldn't want to add a download for each page. How would a user download one of the pages from ana tals?  

If there is not way to include generated downloads for multipage items, maybe we need to stick with Mirador?

**Comment by ewlarson** [comment]
Yeah, they just don't have a download feature/plugin/module for Clover — might a good opportunity to reach out to Northwestern and ask if/when that might be on their roadmap.

If we're sticking with Mirador for the meantime, I'll work in that direction for this week.

**Comment by karenmajewicz** [comment]
skip 4.2

**Comment by ewlarson** [comment]
GeoBlacklight v4.4 running on GeoDev:
https://geodev.btaa.org

**Comment by ewlarson** [comment]
Geoportal v5.6.0 with GBL v4.4 is live in production
