### ISSUE TITLE
Update "About" box on homepage

### ISSUE THREAD

**Issue by karenmajewicz** [geobtaa/geoportal#584]
Include mention of GIN; with link and new logo.

**Comment by karenmajewicz** [comment]
Here is the original JPEG they sent
![GeoSpatial Lock up-2](https://github.com/geobtaa/geoportal/assets/2367677/835da213-5e85-48f5-abdb-1b1aebd008c2)

**Comment by ewlarson** [comment]
On GeoDev:
https://geodev.btaa.org/

![Image](https://github.com/geobtaa/geoportal/assets/69827/ebd3a9ec-acbd-4c04-a097-76443846d370)

**Comment by karenmajewicz** [comment]
Looks good.
