### ISSUE TITLE
Change parameter on leaflet.sleep

### ISSUE THREAD

**Issue by karenmajewicz** [geobtaa/geoportal#591]
The "Click to Wake" function can be unwieldy to use when examining a record and it keeps going back to sleep.  One way to improve this might be the hoverToWake parameter.  It is currently set to "false", which means that the map will go back to sleep while the user is looking at it. The user can still click on features in the web service, but the overlay button "Click to Wake" gets in the way.

If we change this to "true", it will stay awake while the mouse is over it.  You can see the behavior here: http://cliffcloud.github.io/Leaflet.Sleep/

Downside -this might make the map scrolling too prevalent.

**Comment by ewlarson** [comment]
Update in Geoportal v5.6.0.
