### ISSUE TITLE
Reevaluate size and location of the item viewer

### ISSUE THREAD

**Issue by karenmajewicz** [geobtaa/geoportal#592]
This is a ticket to track what might be a larger design issue.

We enlarged the item viewer window (items with IIIF or web services) somewhat recently. This included adjusting the page to a full width as well as making the window itself larger.

Although this privileges a visual preview, it makes the page difficult to navigate. We have experimented with freezing the map scroll using leaflet.sleep, but this causes excessive waking and sleeping messages for the user.  We also added a "Full details" button at the top of the page, but this button is light gray and not very prominent. I actually forgot about it until yesterday.

The main negative user experience I see right now is trying to click on web services or OpenIndexMaps. If a user clicks on a feature, they need to scroll down to see the link. However, this just scrolls the map itself and by the time the users reaches the link, the map might have scrolled out too far to see where they are.

I personally would prefer a shorter default height for the viewer that lets me see below the viewer when I first load the page.

Here are some screenshots from my Macbook:

At default zoom when I first load a page. Although I have clicked a polygon in the OpenIndexMap, you cannot see the metadata or the OpenIndexMap link.

![Image](https://github.com/geobtaa/geoportal/assets/2367677/b7f3b2d5-0df3-4eea-b718-e0da0d3b9f46)

After zooming out as far as possible. I can now see more context, including some of the metadata below the viewer. I find this a lot easier to work with and always have the option of opening the map in full screen to see more. However, the functionality of the OpenIndexMap goes away when I am in full screen.

![Image](https://github.com/geobtaa/geoportal/assets/2367677/2ff99930-5809-4146-be5e-c8ad577957d7)

**Comment by ewlarson** [comment]
Here's the ItemViewer at 600px height with hover to wake:
https://geodev.btaa.org/catalog/33124247-3b19-446b-bc3c-35ddbc0d3155

**Comment by karenmajewicz** [comment]
I do find the layout with 600px more manageable.  I also like the hover to wake option.

**Comment by ewlarson** [comment]
I agree, especially for IndexMaps. We might also remove the "Full Details" header and button now that the viewer ends farther up...?
