### ISSUE TITLE
Click to wake button appears on top of supplemental metadata viewer

### ISSUE THREAD

**Issue by karenmajewicz** [geobtaa/geoportal#593]
When a user clicks the Metadata button to view a supplemental metadata file, the "Click to Wake" button is still present and appears on top of the document. This is fairly minor, but a user cannot actually click the button or make the map wake up while the metadata view is active.

<img width="913" alt="Screenshot 2024-04-17 at 11 07 01 AM" src="https://github.com/geobtaa/geoportal/assets/2367677/a07ecb2b-d805-4d3d-a442-79b4b46c59fe">

**Comment by ewlarson** [comment]
Fixed in develop

![593-click-to-wake](https://github.com/geobtaa/geoportal/assets/69827/6630a280-4c92-4905-bb0b-fab5064237c3)
