### ISSUE TITLE
JS issues

### ISSUE THREAD

**Issue by ewlarson** [geobtaa/geoportal#597]
- [ ] GBL Admin / "Notifications (x)" feature isn't automatically updating
- [x] Geoportal / Results placemarkers not showing
- [x] GBL Admin / Document#new multiple value attrs
- [x] Geoportal / Result item show page pagination
- [x] Map tiles not loading properly / https://geodev.btaa.org/catalog/5d6ae8f7-061a-486c-97d2-a52d308dda57
- [x] Fix TMS viewer
- [x] Add TileJSON viewer
- [x] Add WMTS viewer
- [x] Add XYZ viewer

**Comment by karenmajewicz** [comment]
"Notifications (x)" automatic display feature seems to work now. Create new issue if this is still a problem
