### ISSUE TITLE
Fold the Rights field with a "read more" link to expand

### ISSUE THREAD

**Issue by karenmajewicz** [geobtaa/geoportal#603]
Many of the Rights fields are super long. We should fold them down in the same manner as the Description field.

**Comment by ewlarson** [comment]
Can you please drop an example link? (for before and after pics)

**Comment by karenmajewicz** [comment]
Example of lengthy rights statement: https://geo.btaa.org/catalog/ark:-77981-gmgs0c4sj6k

**Comment by ewlarson** [comment]
### Before
![Image](https://github.com/geobtaa/geoportal/assets/69827/f22c461d-9b19-4d67-a7ad-c136f7e6da91)

### After
![Image](https://github.com/geobtaa/geoportal/assets/69827/323a153f-fe75-449d-b616-ba16625456fd)
