### ISSUE TITLE
Reap the ActiveStorage thumbs

### ISSUE THREAD

**Issue by ewlarson** [geobtaa/geoportal#606]
With Amazon S3 as our new Asset and thumbnail storage option, we no longer need the ActiveStorage thumbnails. We should clear these from the file system to save some disk.

**Comment by ewlarson** [comment]
Let's hold off on this, as our import files are still using ActiveStorage and not AWS

**Comment by karenmajewicz** [comment]
I think this is done. Reopen if now.
